[[redirects]]
    from = "*"
    to = "/index.html"
    status = 200

[[headers]]
    for = "/*"
    [headers.values]
        Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
        X-Frame-Options = "SAMEORIGIN"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"

[[headers]]
    for = "/static/**/*.js"
    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
    for = "/fonts/*"
    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
    for = "/service-worker.js"
    [headers.values]
        Cache-Control = "no-cache"

[[headers]]
    for = "/index.html"
    [headers.values]
        Cache-Control = "no-cache"